version: '3.8'

services:
  nginx:
    container_name: api-gateway
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - service_a
      - service_b

  service_a:
    container_name: service_a
    build:
      context: ./service_a
    ports:
      - "8000:8000"

  service_b:
    container_name: service_b
    build:
      context: ./service_b
    ports:
      - "8001:8000"

  redis-api:
    container_name: redis-api
    build:
      context: ./redis_crud_api
    ports:
      - "8004:8004"

  redis:
    image: redis:bookworm
    container_name: redis-sintra
    ports: 
      - 6379:6379

  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: redis-insight
    ports:
      - 8003:8001